name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: Mali
      fonts:
        - asset: fonts/Mali-SemiBold.ttf
        - asset: fonts/Mali-Regular.ttf
        - asset: fonts/Mali-Medium.ttf
        - asset: fonts/Mali-Light.ttf
        - asset: fonts/Mali-ExtraLight.ttf
        - asset: fonts/Mali-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
